version: "3.7"

x-default-app: &default-app
  RELEASE_NAME: local
  LOCAL_REDIS_MASTER_SERVICE_HOST: redis
  LOCAL_REDIS_MASTER_SERVICE_PORT: 6379
  LOCAL_MONGODB_SERVICE_HOST: mongo
  LOCAL_MONGODB_SERVICE_PORT: 27017
  LOCAL_RABBITMQ_SERVICE_HOST: rabbitmq
  LOCAL_RABBITMQ_SERVICE_PORT_AMQP: 5672
  LOCAL_RABBITMQ_SERVICE_PORT_HTTP_STATS: 15672
  LOCAL_ECOMMERCE_STORE_FRONT_RAILS_SERVICE_HOST: 34.68.51.167
  RABBITMQ_USERNAME: $RABBITMQ_USERNAME
  RABBITMQ_PASSWORD: $RABBITMQ_PASSWORD

x-default-volumes: &default-volumes
  - .:/app
  - tmp:/app/tmp
  - bundle:/app/vendor/bundle

networks:
  network:
    driver: bridge

services:
  app:
    environment:
      <<: *default-app
    volumes: *default-volumes
    image: $IMAGE_NAME:$IMAGE_TAG
    networks:
      - network
    ports:
      - "5600:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:4.2.5
    restart: always
    ports:
      - "5601:27017"
    networks:
      - network

  # hutch:
  #   restart: always
  #   environment:
  #     <<: *default-app
  #   volumes: *default-volumes
  #   image: $IMAGE_NAME:$IMAGE_TAG
  #   networks:
  #     - network
  #   command: bundle exec hutch
  #   depends_on:
  #     - rabbitmq

  # sneakers:
  #   restart: always
  #   environment:
  #     <<: *default-app
  #   volumes: *default-volumes
  #   image: $IMAGE_NAME:$IMAGE_TAG
  #   networks:
  #     - network
  #   command: bin/rake sneakers:run
  #   depends_on:
  #     - rabbitmq

  # rabbitmq:
  #   image: rabbitmq:management
  #   environment:
  #     <<: *default-app
  #     RABBITMQ_ERLANG_COOKIE: d
  #     RABBITMQ_DEFAULT_USER: $RABBITMQ_USERNAME
  #     RABBITMQ_DEFAULT_PASS: $RABBITMQ_PASSWORD
  #   ports:
  #     - 5642:15672
  #   networks:
  #     - network

  redis:
    image: redis
    command: redis-server
    ports:
      - "26379:6379"
    networks:
      - network

volumes:
  tmp:
  bundle:
