apiVersion: skaffold/v2beta10
kind: Config
build:
  artifacts:
  - image: ghcr.io/ikenom/vendor-backend
    sync:
        infer:
        - 'app/**/*.rb'

deploy:
  helm:
    releases:
    - name: vendor-backend
      artifactOverrides:
        image: ghcr.io/ikenom/vendor-backend
      chartPath: chart
      skipBuildDependencies: false
      valuesFiles:
        - ./chart/values.yaml
        - ./chart/values.dev.yaml
      imageStrategy:
        helm: {}
      createNamespace: true
