apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "user-service.fullname" . }}-configmap
data:
  RELEASE_NAME: {{ .Release.Name }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.auth.username }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.auth.password }}
  RAILS_ENV: {{ .Values.railsEnv }}
  SECRET_KEY_BASE: {{ .Values.secretKey }}