apiVersion: v1
kind: Service
metadata:
  name: {{ include "vendor-backend.fullname" . }}-rails
  labels:
    {{- include "vendor-backend.labels" . | nindent 4 }}-rails
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vendor-backend.selectorLabels" . | nindent 4 }}-rails
