{{- if .Values.hutch.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "vendor-backend.fullname" . }}-hutch
  labels:
    {{- include "vendor-backend.labels" . | nindent 4 }}-hutch
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "vendor-backend.fullname" . }}-hutch
  minReplicas: {{ .Values.hutch.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.hutch.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.hutch.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.hutch.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.hutch.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.hutch.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
