production:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "user-service_production") %>

development:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "user-service_development") %>

test:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "user-service_test") %>
