production:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "vendor-backend_production") %>

development:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "vendor-backend_development") %>

test:
  clients:
    default:
      uri: <%= MongoidUriBuilder.build(database_name: "vendor-backend_test") %>
