apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vendor-backend.fullname" . }}-sneakers
  labels:
    {{- include "vendor-backend.labels" . | nindent 4 }}-sneakers
spec:
{{- if not .Values.sneakers.autoscaling.enabled }}
  replicas: {{ .Values.sneakers.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "vendor-backend.selectorLabels" . | nindent 6 }}-sneakers
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "vendor-backend.selectorLabels" . | nindent 8 }}-sneakers
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "vendor-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          command:
            - "bin/rake"
          args:
            - "sneakers:run"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "vendor-backend.fullname" . }}-configmap
          {{ if .Values.railsMasterKey }}
          env:
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: rails-master-key
                key: rails_master_key
          {{ end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
