name: CI

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push image
      run: |
        docker login ghcr.io -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password-stdin <<< ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        docker pull ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}:latest
        docker build . \
          --tag ghcr.io/${{ github.event.repository.owner.login }}/for-testing/${{ github.event.repository.name }}:$GITHUB_SHA \
          --cache-from ghcr.io/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}:latest \
          --label org.opencontainers.image.source=https://github.com/${{ github.event.repository.owner.login }}/${{ github.event.repository.name }}
        docker push ghcr.io/${{ github.event.repository.owner.login }}/for-testing/${{ github.event.repository.name }}:$GITHUB_SHA

  tests:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: |
        docker login ghcr.io -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password-stdin <<< ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        export IMAGE_TAG=$GITHUB_SHA
        script/test
      env:
        IMAGE_NAME: ghcr.io/${{ github.event.repository.owner.login }}/for-testing/${{ github.event.repository.name }}
  lint:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Run linter
      run: |
        docker login ghcr.io -u ${{ secrets.CONTAINER_REGISTRY_USERNAME }} --password-stdin <<< ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}
        export IMAGE_TAG=$GITHUB_SHA
        script/lint
      env:
        IMAGE_NAME: ghcr.io/${{ github.event.repository.owner.login }}/for-testing/${{ github.event.repository.name }}
